/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type { Provider } from '@ethersproject/providers'
import { Contract, type Signer, utils } from 'ethers'
import type {
  IDestinationSettler,
  IDestinationSettlerInterface,
} from '../../ERC7683.sol/IDestinationSettler'

const _abi = [
  {
    type: 'function',
    name: 'fill',
    inputs: [
      {
        name: 'orderId',
        type: 'bytes32',
        internalType: 'bytes32',
      },
      {
        name: 'originData',
        type: 'bytes',
        internalType: 'bytes',
      },
      {
        name: 'fillerData',
        type: 'bytes',
        internalType: 'bytes',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
] as const

export class IDestinationSettler__factory {
  static readonly abi = _abi
  static createInterface(): IDestinationSettlerInterface {
    return new utils.Interface(_abi) as IDestinationSettlerInterface
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider,
  ): IDestinationSettler {
    return new Contract(address, _abi, signerOrProvider) as IDestinationSettler
  }
}
