/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IDestinationSettler } from './IDestinationSettler'
export type { IOriginSettler } from './IOriginSettler'
